import type { Metadata } from "next";
import { Shippori_Mincho } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/header/Header";

const shippori_Mincho = Shippori_Mincho({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "新Bookers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={shippori_Mincho.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
